ModPlug: Allow static and shared linking without extra macros on client
When trying to link a static library without declaring of -DMODPLUG_STATIC, the link fails with lots of undefined references:

```
[100%] Linking C shared library bin\SDL2_mixer_ext.dll
CMakeFiles\SDL2_mixer_ext.dir/objects.a(music_modplug.c.obj): In function `MODPLUG_Load':
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:83: undefined reference to `__imp_ModPlug_Load'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:84: undefined reference to `__imp_ModPlug_Unload'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:85: undefined reference to `__imp_ModPlug_Read'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:86: undefined reference to `__imp_ModPlug_Seek'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:87: undefined reference to `__imp_ModPlug_GetLength'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:88: undefined reference to `__imp_ModPlug_GetSettings'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:89: undefined reference to `__imp_ModPlug_SetSettings'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:90: undefined reference to `__imp_ModPlug_SetMasterVolume'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:91: undefined reference to `__imp_ModPlug_GetName'
C:/Repos/SDL-Mixer-X/src/codecs/music_modplug.c:95: undefined reference to `__imp_ModPlug_Tell'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [CMakeFiles\SDL2_mixer_ext.dir\build.make:476: bin/SDL2_mixer_ext.dll] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:108: CMakeFiles/SDL2_mixer_ext.dir/all] Error 2
mingw32-make.exe: *** [Makefile:129: all] Error 2
```

The `__declspec(dllimport)` is totally unneeded at all: linking will work always for both shared and static libraries. It's totally not need to require clients to declare extra macros for static linking on Windows and make their developer a big headage to figure out for a problem source.